### ISSUE TITLE
Fails to build on GHC 8.10

### ISSUE THREAD

**Issue by kozross** [conal/checkers#49] opened 2020-06-02 01:31 UTC
I got the following when trying to build this (as a dependency for [``natural``](https://github.com/system-f/natural)):

```
Preprocessing library for checkers-0.5.5..
Building library for checkers-0.5.5..
[ 1 of 15] Compiling Control.Monad.Extensions ( src/Control/Monad/Extensions.hs, dist/build/Control/Monad/Extensions.o, dist/build/Control/Monad/Extensions.dyn_o )
[ 2 of 15] Compiling Test.QuickCheck.Bottoms ( src/Test/QuickCheck/Bottoms.hs, dist/build/Test/QuickCheck/Bottoms.o, dist/build/Test/QuickCheck/Bottoms.dyn_o )
[ 3 of 15] Compiling Test.QuickCheck.Instances.Array ( src/Test/QuickCheck/Instances/Array.hs, dist/build/Test/QuickCheck/Instances/Array.o, dist/build/Test/QuickCheck/Instances/Array.dyn_o )
[ 4 of 15] Compiling Test.QuickCheck.Instances.Maybe ( src/Test/QuickCheck/Instances/Maybe.hs, dist/build/Test/QuickCheck/Instances/Maybe.o, dist/build/Test/QuickCheck/Instances/Maybe.dyn_o )
[ 5 of 15] Compiling Test.QuickCheck.Instances.Num ( src/Test/QuickCheck/Instances/Num.hs, dist/build/Test/QuickCheck/Instances/Num.o, dist/build/Test/QuickCheck/Instances/Num.dyn_o )
[ 6 of 15] Compiling Test.QuickCheck.Instances.List ( src/Test/QuickCheck/Instances/List.hs, dist/build/Test/QuickCheck/Instances/List.o, dist/build/Test/QuickCheck/Instances/List.dyn_o )
[ 7 of 15] Compiling Test.QuickCheck.Instances.Ord ( src/Test/QuickCheck/Instances/Ord.hs, dist/build/Test/QuickCheck/Instances/Ord.o, dist/build/Test/QuickCheck/Instances/Ord.dyn_o )
[ 8 of 15] Compiling Test.QuickCheck.Instances.Tuple ( src/Test/QuickCheck/Instances/Tuple.hs, dist/build/Test/QuickCheck/Instances/Tuple.o, dist/build/Test/QuickCheck/Instances/Tuple.dyn_o )
[ 9 of 15] Compiling Test.QuickCheck.Utils ( src/Test/QuickCheck/Utils.hs, dist/build/Test/QuickCheck/Utils.o, dist/build/Test/QuickCheck/Utils.dyn_o )
[10 of 15] Compiling Test.QuickCheck.Checkers ( src/Test/QuickCheck/Checkers.hs, dist/build/Test/QuickCheck/Checkers.o, dist/build/Test/QuickCheck/Checkers.dyn_o )

src/Test/QuickCheck/Checkers.hs:256:30: error:
    Ambiguous occurrence ‘First’
    It could refer to
       either ‘Data.Monoid.First’,
              imported from ‘Data.Monoid’ at src/Test/QuickCheck/Checkers.hs:(53,1)-(57,27)
           or ‘Data.Semigroup.First’,
              imported from ‘Data.Semigroup’ at src/Test/QuickCheck/Checkers.hs:69:1-21
    |
256 | instance EqProp a => EqProp (First a)
    |                              ^^^^^

src/Test/QuickCheck/Checkers.hs:257:30: error:
    Ambiguous occurrence ‘Last’
    It could refer to
       either ‘Data.Monoid.Last’,
              imported from ‘Data.Monoid’ at src/Test/QuickCheck/Checkers.hs:(53,1)-(57,27)
           or ‘Data.Semigroup.Last’,
              imported from ‘Data.Semigroup’ at src/Test/QuickCheck/Checkers.hs:69:1-21
    |
257 | instance EqProp a => EqProp (Last a)
    |                              ^^^^
```

Edit: For clarification, this is with regard to [this issue here](https://github.com/system-f/natural/issues/5).

**Comment by sjakobi** [comment] 2020-06-02 09:23
Duplicate of #44, which has been fixed on `master` but hasn't been released to Hackage yet.

@kozross, for now you could simply use v0.5.4.

**Comment by sjakobi** [comment] 2020-06-19 00:03
I've uploaded [v0.5.6](https://hackage.haskell.org/package/checkers-0.5.6) now, and deprecated v0.5.5.

**Closed by sjakobi** 2020-06-19 00:03 UTC
